alias g=git
alias ga='git add'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit'
alias gd='git diff'
alias gf='git fetch'
alias gl='git log'
alias gl1='git log --oneline'
alias gla='git log --oneline --graph --all'
alias glb='git log --oneline --graph --branches'
alias gm='git merge'
alias gp='git pull'
alias gr='git remote -v'
alias gs='git status'
alias gt='git tag'
alias gu='git restore'

